- include_tasks:
    file: run.yml
    apply:
      tags:
        - run
  tags:
    - run
    - run.tmux-kill
    - run.qalpl
    - run.rcc
    - run.only
    - run.ruby
    - run.xetchy
    - run.split
    - run.hosts