---
- name: Kill existing tmux session
  shell: |
    tmux kill-server || true
  args:
    executable: /bin/bash
  tags:
    - run.tmux-kill
    - run.qalpl
    - run.rcc

- name: Launch tmux session
  shell: |
    tmux set-option remain-on-exit on
    tmux setw remain-on-exit on
    tmux new-session -d -s rcc -n workspace 'bash -l'
    tmux new-window -n htop -t rcc: 'htop'
  args:
    executable: /bin/bash
  tags:
    - run.qalpl
    - run.rcc
    - run.only
#
# Run the qalpl scripts, better to be use with --limit host
#
# --max_old_space_size=4096
- name: Run qalpl.js script in a tmux windows (https://www.epfl.ch 2 3)
  shell: |
    tmux new-window -n www -t rcc: 'cd /srv/rcc; date; export NODE_OPTIONS="--max-old-space-size=4096"; time node qalpl.js https://www.epfl.ch 2 2; date; bash'
  when: inventory_hostname == 'qalpl01'
  tags:
    - run.qalpl
    - run.only

- name: Run qalpl.js script in a tmux windows (https://www.epfl.ch/fr 2 3)
  shell: |
    tmux new-window -n www_fr -t rcc: 'cd /srv/rcc; date; time node qalpl.js https://www.epfl.ch/fr/ 2 2; date; bash'
  when: inventory_hostname == 'qalpl02'
  tags:
    - run.qalpl

- name: Run qalpl.js script in a tmux windows (https://www.epfl.ch/labs 2 3)
  shell: |
    tmux new-window -n labs -t rcc: 'cd /srv/rcc; date; time node qalpl.js https://www.epfl.ch/labs 2 2; date; bash'
  when: inventory_hostname == 'qalpl03'
  tags:
    - run.qalpl

- name: Run qalpl.js script in a tmux windows (https://www.epfl.ch/labs/fr 2 3)
  shell: |
    tmux new-window -n labs_fr -t rcc: 'cd /srv/rcc; date; time node qalpl.js https://www.epfl.ch/labs/fr/ 2 2; date; bash'
  when: inventory_hostname == 'qalpl04'
  tags:
    - run.qalpl

- name: Run qalpl.js script in a tmux windows (https://www.epfl.ch/campus/associations/list/ 2 3)
  shell: |
    tmux new-window -n assoc_lst -t rcc: 'cd /srv/rcc; date; time node qalpl.js https://www.epfl.ch/campus/associations/list/ 2 2; date; bash'
  when: inventory_hostname == 'qalpl0x'
  tags:
    - run.qalpl

- name: Run qalpl.js script in a tmux windows (https://www.epfl.ch/campus/associations/list/ 2 3)
  shell: |
    tmux new-window -n assoc_lst_fr -t rcc: 'cd /srv/rcc; date; time node qalpl.js https://www.epfl.ch/campus/associations/list/fr/ 2 2; date; bash'
  when: inventory_hostname == 'qalpl0x'
  tags:
    - run.qalpl


#
# Run part of url file with the RCC script
#
- name: Run rcc script in a tmux windows on qalpl01
  shell: |
    tmux new-window -n rcc -t rcc: 'cd /srv/rcc; date; time npm start -- --file '../urls_clean_splitted_00.txt' --performance true --report --useragent FSD --no-screenshot; date; bash'
  when: inventory_hostname == 'qalpl01'
  tags:
    - run.rcc

- name: Run rcc script in a tmux windows on qalpl02
  shell: |
    tmux new-window -n rcc -t rcc: 'cd /srv/rcc; date; time npm start -- --file '../urls_clean_splitted_01.txt' --performance true --report --useragent FSD --no-screenshot; date; bash'
  when: inventory_hostname == 'qalpl02'
  tags:
    - run.rcc

- name: Run rcc script in a tmux windows on qalpl03
  shell: |
    tmux new-window -n rcc -t rcc: 'cd /srv/rcc; date; time npm start -- --file '../urls_clean_splitted_02.txt' --performance true --report --useragent FSD --no-screenshot; date; bash'
  when: inventory_hostname == 'qalpl03'
  tags:
    - run.rcc

- name: Run rcc script in a tmux windows on qalpl04
  shell: |
    tmux new-window -n rcc -t rcc: 'cd /srv/rcc; date; time npm start -- --file '../urls_clean_splitted_03.txt' --performance true --report --useragent FSD --no-screenshot; date; bash'
  when: inventory_hostname == 'qalpl04'
  tags:
    - run.rcc
