---
- name: Kill existing tmux session
  shell: |
    tmux kill-server || true
  args:
    executable: /bin/bash
  tags:
    - run.tmux-kill
    - run.qalpl
    - run.rcc
    - run.only
    - run.xetchy
    - run.ruby
    - run.split

- name: Launch tmux session
  shell: |
    tmux set-option remain-on-exit on
    tmux setw remain-on-exit on
    tmux new-session -d -s rcc -n workspace 'bash -l'
    tmux new-window -n htop -t rcc: 'htop'
  args:
    executable: /bin/bash
  tags:
    - run.qalpl
    - run.rcc
    - run.only
    - run.xetchy
    - run.ruby
    - run.split

# - name: Run fetch_all_urls.rb
#   shell: |
#     tmux new-window -n ruby -t rcc: 'cd /srv/rcc; date; rm urls.txt; ruby fetch_all_urls.rb; date; bash'
#   tags:
#     - run.ruby

- name: Run xetchy
  shell: |
    tmux new-window -n xetchy -t rcc: 'cd /srv/rcc; date; rm urls.txt; node xetchy.js; date; cat urls.txt | sort -u > urls_unq.txt; mv urls_unq.txt urls.txt; bash'
  tags:
    - run.xetchy

- name: Split the urls file
  shell: |
    tmux new-window -n split -t rcc: 'cd /srv/rcc; ./split.sh urls.txt 12; cat urls_splitted_12.txt >> urls_splitted_11.txt && rm urls_splitted_12.txt; bash'
  tags:
    - run.split

- name: Force varnish reload
  lineinfile:
    path: "/etc/hosts"
    state: present
    line: "128.178.222.83 www.epfl.ch"
  become: yes
  tags:
    - run.hosts

#
# Run part of url file with the RCC script  urls_no_slash_splitted_
#
- name: Run rcc script in a tmux windows on qalpl01
  shell: |
    tmux new-window -n rcc00 -t rcc: 'cd /srv/rcc; date; time npm start -- --file 'urls_splitted_00.txt' --performance true --report --useragent RCC-IDEVFSD --no-screenshot --dimension 1300,1000; date; bash'
    tmux new-window -n rcc01 -t rcc: 'cd /srv/rcc; date; time npm start -- --file 'urls_splitted_01.txt' --performance true --report --useragent RCC-IDEVFSD --no-screenshot --dimension 1300,1000; date; bash'
    tmux new-window -n rcc02 -t rcc: 'cd /srv/rcc; date; time npm start -- --file 'urls_splitted_02.txt' --performance true --report --useragent RCC-IDEVFSD --no-screenshot --dimension 1300,1000; date; bash'
  when: inventory_hostname == 'qalpl01'
  tags:
    - run.rcc

- name: Run rcc script in a tmux windows on qalpl02
  shell: |
    tmux new-window -n rcc03 -t rcc: 'cd /srv/rcc; date; time npm start -- --file 'urls_splitted_03.txt' --performance true --report --useragent RCC-IDEVFSD --no-screenshot --dimension 1300,1000; date; bash'
    tmux new-window -n rcc04 -t rcc: 'cd /srv/rcc; date; time npm start -- --file 'urls_splitted_04.txt' --performance true --report --useragent RCC-IDEVFSD --no-screenshot --dimension 1300,1000; date; bash'
    tmux new-window -n rcc05 -t rcc: 'cd /srv/rcc; date; time npm start -- --file 'urls_splitted_05.txt' --performance true --report --useragent RCC-IDEVFSD --no-screenshot --dimension 1300,1000; date; bash'
  when: inventory_hostname == 'qalpl02'
  tags:
    - run.rcc

- name: Run rcc script in a tmux windows on qalpl03
  shell: |
    tmux new-window -n rcc06 -t rcc: 'cd /srv/rcc; date; time npm start -- --file 'urls_splitted_06.txt' --performance true --report --useragent RCC-IDEVFSD --no-screenshot --dimension 1300,1000; date; bash'
    tmux new-window -n rcc07 -t rcc: 'cd /srv/rcc; date; time npm start -- --file 'urls_splitted_07.txt' --performance true --report --useragent RCC-IDEVFSD --no-screenshot --dimension 1300,1000; date; bash'
    tmux new-window -n rcc08 -t rcc: 'cd /srv/rcc; date; time npm start -- --file 'urls_splitted_08.txt' --performance true --report --useragent RCC-IDEVFSD --no-screenshot --dimension 1300,1000; date; bash'
  when: inventory_hostname == 'qalpl03'
  tags:
    - run.rcc

- name: Run rcc script in a tmux windows on qalpl04
  shell: |
    tmux new-window -n rcc09 -t rcc: 'cd /srv/rcc; date; time npm start -- --file 'urls_splitted_09.txt' --performance true --report --useragent RCC-IDEVFSD --no-screenshot --dimension 1300,1000; date; bash'
    tmux new-window -n rcc10 -t rcc: 'cd /srv/rcc; date; time npm start -- --file 'urls_splitted_10.txt' --performance true --report --useragent RCC-IDEVFSD --no-screenshot --dimension 1300,1000; date; bash'
    tmux new-window -n rcc11 -t rcc: 'cd /srv/rcc; date; time npm start -- --file 'urls_splitted_11.txt' --performance true --report --useragent RCC-IDEVFSD --no-screenshot --dimension 1300,1000; date; bash'
  when: inventory_hostname == 'qalpl04'
  tags:
    - run.rcc

#
# Run the qalpl scripts, better to be use with --limit host
#
# --max_old_space_size=4096
# - name: Run qalpl.js script in a tmux windows (https://www.epfl.ch 2 3)
#   shell: |
#     tmux new-window -n www -t rcc: 'cd /srv/rcc; date; export NODE_OPTIONS="--max-old-space-size=4096"; time node qalpl.js https://www.epfl.ch 2 2; date; bash'
#   when: inventory_hostname == 'qalpl01'
#   tags:
#     - run.qalpl
#     #- run.only
#
# - name: Run qalpl.js script in a tmux windows (https://www.epfl.ch/fr 2 3)
#   shell: |
#     tmux new-window -n www_fr -t rcc: 'cd /srv/rcc; date; time node qalpl.js https://www.epfl.ch/fr/ 2 2; date; bash'
#   when: inventory_hostname == 'qalpl02'
#   tags:
#     - run.qalpl
#     - run.only
#
# - name: Run qalpl.js script in a tmux windows (https://www.epfl.ch/labs 2 3)
#   shell: |
#     tmux new-window -n labs -t rcc: 'cd /srv/rcc; date; time node qalpl.js https://www.epfl.ch/labs 2 2; date; bash'
#   when: inventory_hostname == 'qalpl03'
#   tags:
#     - run.qalpl
#
# - name: Run qalpl.js script in a tmux windows (https://www.epfl.ch/labs/fr 2 3)
#   shell: |
#     tmux new-window -n labs_fr -t rcc: 'cd /srv/rcc; date; time node qalpl.js https://www.epfl.ch/labs/fr/ 2 2; date; bash'
#   when: inventory_hostname == 'qalpl04'
#   tags:
#     - run.qalpl
#
# - name: Run qalpl.js script in a tmux windows (https://www.epfl.ch/campus/associations/list/ 2 3)
#   shell: |
#     tmux new-window -n assoc_lst -t rcc: 'cd /srv/rcc; date; time node qalpl.js https://www.epfl.ch/campus/associations/list/ 2 2; date; bash'
#   when: inventory_hostname == 'qalpl0x'
#   tags:
#     - run.qalpl
#
# - name: Run qalpl.js script in a tmux windows (https://www.epfl.ch/campus/associations/list/ 2 3)
#   shell: |
#     tmux new-window -n assoc_lst_fr -t rcc: 'cd /srv/rcc; date; time node qalpl.js https://www.epfl.ch/campus/associations/list/fr/ 2 2; date; bash'
#   when: inventory_hostname == 'qalpl0x'
#   tags:
#     - run.qalpl

# - name: Run qalpl.js script in a tmux windows (https://www.epfl.ch)
#   shell: |
#     tmux new-window -n assoc_lst_fr -t rcc: 'cd /srv/rcc; date; time node qalpl.js https://www.epfl.ch/; date; bash'
#   when: inventory_hostname == 'qalpl04'
#   tags:
#     - run.qalpl
