- include_tasks:
    file: softs.yml
    apply:
      tags:
        - softs
  tags:
    - softs
    - softs.install
    - softs.config
    - softs.ruby

- include_tasks:
    file: swap.yml
    apply:
      tags:
        - swap
  tags:
    - swap

