---
- name: "Create {{ rcc_install_path }}"
  file:
    path: "{{ rcc_install_path }}"
    state: directory
    mode: '0775'
    owner: ubuntu
    group: ubuntu
  become: yes
  tags:
    - deploy.dir

- name: "Ensure that /srv is writable"
  file:
    path: /srv
    state: directory
    mode: '0775'
    owner: ubuntu
    group: ubuntu
  become: yes
  tags:
    - deploy.dir

- name: Clone/Update rcc
  git:
    repo: 'https://github.com/epfl-si/rcc.git'
    dest: "{{ rcc_install_path }}"
    update: yes
    force: yes
  tags:
    - deploy.clone

- name: Running npm i
  shell: |
    cd "{{ rcc_install_path }}"
    npm i --no-fund
  become: yes
  tags:
    - deploy.npm
